apiVersion: v2
name: multus-cni
description: A Helm chart top deploy multus-cni
type: application
version: 4.2.3
appVersion: 4.2.3
dependencies:
- name: crds
  version: "0.0.*"
  condition: crds.plain