apiVersion: v2
name: kubevirt-operator
description: KubeVirt Operator
type: application
version: 1.7.0-rc.1
appVersion: 1.7.0-rc.1
dependencies:
- name: crds
  version: "0.0.*"
  condition: crds.plain
